name: one_store
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_rating_bar: ^4.0.1
  circle_nav_bar:
  flutter_staggered_grid_view:
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  provider: ^5.0.0
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

 
  assets:
    - assets/image/
    - assets/image/banner/
    - assets/image/category/
    - assets/image/book/
    - assets/layout/
    - assets/image/admin/
    - assets/files/booklist.json
    - assets/files/stationerylist.json
    - assets/files/userlist.json
    - assets/files/orderlist.json
    - assets/files/promotionlist.json
    - assets/files/categorylist.json





 
